name: gamepaper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.8

  provider: ^6.0.1
  cached_network_image: ^3.4.0
  card_swiper : ^3.0.1

  #배경화면 설정 관련 패키지
  flutter_cache_manager: ^3.0.0
  async_wallpaper: ^2.1.0

  #게임 목록 캐로셀 스크롤
  carousel_slider_plus: ^7.0.0

  #배경화면 목록 페이징
  smooth_page_indicator: ^1.2.0+3
  #환경변수
  flutter_dotenv: ^5.1.0
  #파이어베이스
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  firebase_app_check: ^0.3.0+4
  firebase_auth: ^5.1.4

  flutter_blurhash: ^0.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  #앱 아이콘 관련 패키지
  flutter_launcher_icons: ^0.13.1
  #패키지 이름 변경
  change_app_package_name: ^1.3.0
#아이콘 설정
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # assets:

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700